// Generated by gencpp from file pose_graph_tools/BowQuery.msg
// DO NOT EDIT!


#ifndef POSE_GRAPH_TOOLS_MESSAGE_BOWQUERY_H
#define POSE_GRAPH_TOOLS_MESSAGE_BOWQUERY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <pose_graph_tools/BowVector.h>

namespace pose_graph_tools
{
template <class ContainerAllocator>
struct BowQuery_
{
  typedef BowQuery_<ContainerAllocator> Type;

  BowQuery_()
    : robot_id(0)
    , pose_id(0)
    , bow_vector()  {
    }
  BowQuery_(const ContainerAllocator& _alloc)
    : robot_id(0)
    , pose_id(0)
    , bow_vector(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _robot_id_type;
  _robot_id_type robot_id;

   typedef uint32_t _pose_id_type;
  _pose_id_type pose_id;

   typedef  ::pose_graph_tools::BowVector_<ContainerAllocator>  _bow_vector_type;
  _bow_vector_type bow_vector;





  typedef boost::shared_ptr< ::pose_graph_tools::BowQuery_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pose_graph_tools::BowQuery_<ContainerAllocator> const> ConstPtr;

}; // struct BowQuery_

typedef ::pose_graph_tools::BowQuery_<std::allocator<void> > BowQuery;

typedef boost::shared_ptr< ::pose_graph_tools::BowQuery > BowQueryPtr;
typedef boost::shared_ptr< ::pose_graph_tools::BowQuery const> BowQueryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pose_graph_tools::BowQuery_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pose_graph_tools::BowQuery_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pose_graph_tools::BowQuery_<ContainerAllocator1> & lhs, const ::pose_graph_tools::BowQuery_<ContainerAllocator2> & rhs)
{
  return lhs.robot_id == rhs.robot_id &&
    lhs.pose_id == rhs.pose_id &&
    lhs.bow_vector == rhs.bow_vector;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pose_graph_tools::BowQuery_<ContainerAllocator1> & lhs, const ::pose_graph_tools::BowQuery_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pose_graph_tools

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pose_graph_tools::BowQuery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_graph_tools::BowQuery_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_graph_tools::BowQuery_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_graph_tools::BowQuery_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_graph_tools::BowQuery_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_graph_tools::BowQuery_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pose_graph_tools::BowQuery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a0cd5fc0bc344c45715e8fad77418231";
  }

  static const char* value(const ::pose_graph_tools::BowQuery_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa0cd5fc0bc344c45ULL;
  static const uint64_t static_value2 = 0x715e8fad77418231ULL;
};

template<class ContainerAllocator>
struct DataType< ::pose_graph_tools::BowQuery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pose_graph_tools/BowQuery";
  }

  static const char* value(const ::pose_graph_tools::BowQuery_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pose_graph_tools::BowQuery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 robot_id\n"
"uint32 pose_id\n"
"BowVector bow_vector\n"
"================================================================================\n"
"MSG: pose_graph_tools/BowVector\n"
"uint32[] word_ids\n"
"float32[] word_values\n"
;
  }

  static const char* value(const ::pose_graph_tools::BowQuery_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pose_graph_tools::BowQuery_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_id);
      stream.next(m.pose_id);
      stream.next(m.bow_vector);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BowQuery_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pose_graph_tools::BowQuery_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pose_graph_tools::BowQuery_<ContainerAllocator>& v)
  {
    s << indent << "robot_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.robot_id);
    s << indent << "pose_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.pose_id);
    s << indent << "bow_vector: ";
    s << std::endl;
    Printer< ::pose_graph_tools::BowVector_<ContainerAllocator> >::stream(s, indent + "  ", v.bow_vector);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSE_GRAPH_TOOLS_MESSAGE_BOWQUERY_H
