// Generated by gencpp from file pose_graph_tools/LcdFrameRegistration.msg
// DO NOT EDIT!


#ifndef POSE_GRAPH_TOOLS_MESSAGE_LCDFRAMEREGISTRATION_H
#define POSE_GRAPH_TOOLS_MESSAGE_LCDFRAMEREGISTRATION_H

#include <ros/service_traits.h>


#include <pose_graph_tools/LcdFrameRegistrationRequest.h>
#include <pose_graph_tools/LcdFrameRegistrationResponse.h>


namespace pose_graph_tools
{

struct LcdFrameRegistration
{

typedef LcdFrameRegistrationRequest Request;
typedef LcdFrameRegistrationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LcdFrameRegistration
} // namespace pose_graph_tools


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pose_graph_tools::LcdFrameRegistration > {
  static const char* value()
  {
    return "35f0b877789b9625f9ce0e88684ba2e8";
  }

  static const char* value(const ::pose_graph_tools::LcdFrameRegistration&) { return value(); }
};

template<>
struct DataType< ::pose_graph_tools::LcdFrameRegistration > {
  static const char* value()
  {
    return "pose_graph_tools/LcdFrameRegistration";
  }

  static const char* value(const ::pose_graph_tools::LcdFrameRegistration&) { return value(); }
};


// service_traits::MD5Sum< ::pose_graph_tools::LcdFrameRegistrationRequest> should match
// service_traits::MD5Sum< ::pose_graph_tools::LcdFrameRegistration >
template<>
struct MD5Sum< ::pose_graph_tools::LcdFrameRegistrationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pose_graph_tools::LcdFrameRegistration >::value();
  }
  static const char* value(const ::pose_graph_tools::LcdFrameRegistrationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pose_graph_tools::LcdFrameRegistrationRequest> should match
// service_traits::DataType< ::pose_graph_tools::LcdFrameRegistration >
template<>
struct DataType< ::pose_graph_tools::LcdFrameRegistrationRequest>
{
  static const char* value()
  {
    return DataType< ::pose_graph_tools::LcdFrameRegistration >::value();
  }
  static const char* value(const ::pose_graph_tools::LcdFrameRegistrationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pose_graph_tools::LcdFrameRegistrationResponse> should match
// service_traits::MD5Sum< ::pose_graph_tools::LcdFrameRegistration >
template<>
struct MD5Sum< ::pose_graph_tools::LcdFrameRegistrationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pose_graph_tools::LcdFrameRegistration >::value();
  }
  static const char* value(const ::pose_graph_tools::LcdFrameRegistrationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pose_graph_tools::LcdFrameRegistrationResponse> should match
// service_traits::DataType< ::pose_graph_tools::LcdFrameRegistration >
template<>
struct DataType< ::pose_graph_tools::LcdFrameRegistrationResponse>
{
  static const char* value()
  {
    return DataType< ::pose_graph_tools::LcdFrameRegistration >::value();
  }
  static const char* value(const ::pose_graph_tools::LcdFrameRegistrationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POSE_GRAPH_TOOLS_MESSAGE_LCDFRAMEREGISTRATION_H
