// Generated by gencpp from file pose_graph_tools/LcdFrameRegistrationResponse.msg
// DO NOT EDIT!


#ifndef POSE_GRAPH_TOOLS_MESSAGE_LCDFRAMEREGISTRATIONRESPONSE_H
#define POSE_GRAPH_TOOLS_MESSAGE_LCDFRAMEREGISTRATIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace pose_graph_tools
{
template <class ContainerAllocator>
struct LcdFrameRegistrationResponse_
{
  typedef LcdFrameRegistrationResponse_<ContainerAllocator> Type;

  LcdFrameRegistrationResponse_()
    : valid(false)
    , match_T_query()  {
    }
  LcdFrameRegistrationResponse_(const ContainerAllocator& _alloc)
    : valid(false)
    , match_T_query(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _valid_type;
  _valid_type valid;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _match_T_query_type;
  _match_T_query_type match_T_query;





  typedef boost::shared_ptr< ::pose_graph_tools::LcdFrameRegistrationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pose_graph_tools::LcdFrameRegistrationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LcdFrameRegistrationResponse_

typedef ::pose_graph_tools::LcdFrameRegistrationResponse_<std::allocator<void> > LcdFrameRegistrationResponse;

typedef boost::shared_ptr< ::pose_graph_tools::LcdFrameRegistrationResponse > LcdFrameRegistrationResponsePtr;
typedef boost::shared_ptr< ::pose_graph_tools::LcdFrameRegistrationResponse const> LcdFrameRegistrationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pose_graph_tools::LcdFrameRegistrationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pose_graph_tools::LcdFrameRegistrationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pose_graph_tools::LcdFrameRegistrationResponse_<ContainerAllocator1> & lhs, const ::pose_graph_tools::LcdFrameRegistrationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.valid == rhs.valid &&
    lhs.match_T_query == rhs.match_T_query;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pose_graph_tools::LcdFrameRegistrationResponse_<ContainerAllocator1> & lhs, const ::pose_graph_tools::LcdFrameRegistrationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pose_graph_tools

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pose_graph_tools::LcdFrameRegistrationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_graph_tools::LcdFrameRegistrationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_graph_tools::LcdFrameRegistrationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_graph_tools::LcdFrameRegistrationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_graph_tools::LcdFrameRegistrationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_graph_tools::LcdFrameRegistrationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pose_graph_tools::LcdFrameRegistrationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c544cb47163024a80f51b3b120d56c3a";
  }

  static const char* value(const ::pose_graph_tools::LcdFrameRegistrationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc544cb47163024a8ULL;
  static const uint64_t static_value2 = 0x0f51b3b120d56c3aULL;
};

template<class ContainerAllocator>
struct DataType< ::pose_graph_tools::LcdFrameRegistrationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pose_graph_tools/LcdFrameRegistrationResponse";
  }

  static const char* value(const ::pose_graph_tools::LcdFrameRegistrationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pose_graph_tools::LcdFrameRegistrationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool valid\n"
"geometry_msgs/Pose match_T_query\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::pose_graph_tools::LcdFrameRegistrationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pose_graph_tools::LcdFrameRegistrationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.valid);
      stream.next(m.match_T_query);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LcdFrameRegistrationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pose_graph_tools::LcdFrameRegistrationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pose_graph_tools::LcdFrameRegistrationResponse_<ContainerAllocator>& v)
  {
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
    s << indent << "match_T_query: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.match_T_query);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSE_GRAPH_TOOLS_MESSAGE_LCDFRAMEREGISTRATIONRESPONSE_H
