// Generated by gencpp from file pose_graph_tools/LoopClosures.msg
// DO NOT EDIT!


#ifndef POSE_GRAPH_TOOLS_MESSAGE_LOOPCLOSURES_H
#define POSE_GRAPH_TOOLS_MESSAGE_LOOPCLOSURES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <pose_graph_tools/PoseGraphEdge.h>

namespace pose_graph_tools
{
template <class ContainerAllocator>
struct LoopClosures_
{
  typedef LoopClosures_<ContainerAllocator> Type;

  LoopClosures_()
    : publishing_robot_id(0)
    , destination_robot_id(0)
    , edges()  {
    }
  LoopClosures_(const ContainerAllocator& _alloc)
    : publishing_robot_id(0)
    , destination_robot_id(0)
    , edges(_alloc)  {
  (void)_alloc;
    }



   typedef uint16_t _publishing_robot_id_type;
  _publishing_robot_id_type publishing_robot_id;

   typedef uint16_t _destination_robot_id_type;
  _destination_robot_id_type destination_robot_id;

   typedef std::vector< ::pose_graph_tools::PoseGraphEdge_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::pose_graph_tools::PoseGraphEdge_<ContainerAllocator> >> _edges_type;
  _edges_type edges;





  typedef boost::shared_ptr< ::pose_graph_tools::LoopClosures_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pose_graph_tools::LoopClosures_<ContainerAllocator> const> ConstPtr;

}; // struct LoopClosures_

typedef ::pose_graph_tools::LoopClosures_<std::allocator<void> > LoopClosures;

typedef boost::shared_ptr< ::pose_graph_tools::LoopClosures > LoopClosuresPtr;
typedef boost::shared_ptr< ::pose_graph_tools::LoopClosures const> LoopClosuresConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pose_graph_tools::LoopClosures_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pose_graph_tools::LoopClosures_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pose_graph_tools::LoopClosures_<ContainerAllocator1> & lhs, const ::pose_graph_tools::LoopClosures_<ContainerAllocator2> & rhs)
{
  return lhs.publishing_robot_id == rhs.publishing_robot_id &&
    lhs.destination_robot_id == rhs.destination_robot_id &&
    lhs.edges == rhs.edges;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pose_graph_tools::LoopClosures_<ContainerAllocator1> & lhs, const ::pose_graph_tools::LoopClosures_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pose_graph_tools

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pose_graph_tools::LoopClosures_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_graph_tools::LoopClosures_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_graph_tools::LoopClosures_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_graph_tools::LoopClosures_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_graph_tools::LoopClosures_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_graph_tools::LoopClosures_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pose_graph_tools::LoopClosures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f4b270327fa0c480a57687e4837bab6";
  }

  static const char* value(const ::pose_graph_tools::LoopClosures_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f4b270327fa0c48ULL;
  static const uint64_t static_value2 = 0x0a57687e4837bab6ULL;
};

template<class ContainerAllocator>
struct DataType< ::pose_graph_tools::LoopClosures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pose_graph_tools/LoopClosures";
  }

  static const char* value(const ::pose_graph_tools::LoopClosures_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pose_graph_tools::LoopClosures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 publishing_robot_id\n"
"uint16 destination_robot_id\n"
"pose_graph_tools/PoseGraphEdge[] edges\n"
"================================================================================\n"
"MSG: pose_graph_tools/PoseGraphEdge\n"
"Header header\n"
"\n"
"uint64 key_from\n"
"uint64 key_to\n"
"\n"
"int32 robot_from\n"
"int32 robot_to\n"
"\n"
"int32 type\n"
"\n"
"# Type enums\n"
"int32 ODOM      = 0\n"
"int32 LOOPCLOSE = 1\n"
"int32 LANDMARK  = 2\n"
"int32 REJECTED_LOOPCLOSE = 3\n"
"int32 MESH = 4\n"
"int32 POSE_MESH = 5\n"
"int32 MESH_POSE = 6\n"
"\n"
"# Transforms in ede\n"
"geometry_msgs/Pose pose\n"
"float64[36] covariance\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::pose_graph_tools::LoopClosures_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pose_graph_tools::LoopClosures_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.publishing_robot_id);
      stream.next(m.destination_robot_id);
      stream.next(m.edges);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoopClosures_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pose_graph_tools::LoopClosures_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pose_graph_tools::LoopClosures_<ContainerAllocator>& v)
  {
    s << indent << "publishing_robot_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.publishing_robot_id);
    s << indent << "destination_robot_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.destination_robot_id);
    s << indent << "edges[]" << std::endl;
    for (size_t i = 0; i < v.edges.size(); ++i)
    {
      s << indent << "  edges[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::pose_graph_tools::PoseGraphEdge_<ContainerAllocator> >::stream(s, indent + "    ", v.edges[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSE_GRAPH_TOOLS_MESSAGE_LOOPCLOSURES_H
