// Generated by gencpp from file pose_graph_tools/PoseGraphQuery.msg
// DO NOT EDIT!


#ifndef POSE_GRAPH_TOOLS_MESSAGE_POSEGRAPHQUERY_H
#define POSE_GRAPH_TOOLS_MESSAGE_POSEGRAPHQUERY_H

#include <ros/service_traits.h>


#include <pose_graph_tools/PoseGraphQueryRequest.h>
#include <pose_graph_tools/PoseGraphQueryResponse.h>


namespace pose_graph_tools
{

struct PoseGraphQuery
{

typedef PoseGraphQueryRequest Request;
typedef PoseGraphQueryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PoseGraphQuery
} // namespace pose_graph_tools


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pose_graph_tools::PoseGraphQuery > {
  static const char* value()
  {
    return "40dc150d34e522c5c9dc2d4c5d84a9d7";
  }

  static const char* value(const ::pose_graph_tools::PoseGraphQuery&) { return value(); }
};

template<>
struct DataType< ::pose_graph_tools::PoseGraphQuery > {
  static const char* value()
  {
    return "pose_graph_tools/PoseGraphQuery";
  }

  static const char* value(const ::pose_graph_tools::PoseGraphQuery&) { return value(); }
};


// service_traits::MD5Sum< ::pose_graph_tools::PoseGraphQueryRequest> should match
// service_traits::MD5Sum< ::pose_graph_tools::PoseGraphQuery >
template<>
struct MD5Sum< ::pose_graph_tools::PoseGraphQueryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pose_graph_tools::PoseGraphQuery >::value();
  }
  static const char* value(const ::pose_graph_tools::PoseGraphQueryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pose_graph_tools::PoseGraphQueryRequest> should match
// service_traits::DataType< ::pose_graph_tools::PoseGraphQuery >
template<>
struct DataType< ::pose_graph_tools::PoseGraphQueryRequest>
{
  static const char* value()
  {
    return DataType< ::pose_graph_tools::PoseGraphQuery >::value();
  }
  static const char* value(const ::pose_graph_tools::PoseGraphQueryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pose_graph_tools::PoseGraphQueryResponse> should match
// service_traits::MD5Sum< ::pose_graph_tools::PoseGraphQuery >
template<>
struct MD5Sum< ::pose_graph_tools::PoseGraphQueryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pose_graph_tools::PoseGraphQuery >::value();
  }
  static const char* value(const ::pose_graph_tools::PoseGraphQueryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pose_graph_tools::PoseGraphQueryResponse> should match
// service_traits::DataType< ::pose_graph_tools::PoseGraphQuery >
template<>
struct DataType< ::pose_graph_tools::PoseGraphQueryResponse>
{
  static const char* value()
  {
    return DataType< ::pose_graph_tools::PoseGraphQuery >::value();
  }
  static const char* value(const ::pose_graph_tools::PoseGraphQueryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POSE_GRAPH_TOOLS_MESSAGE_POSEGRAPHQUERY_H
