// Generated by gencpp from file pose_graph_tools/TimeRangeQuery.msg
// DO NOT EDIT!


#ifndef POSE_GRAPH_TOOLS_MESSAGE_TIMERANGEQUERY_H
#define POSE_GRAPH_TOOLS_MESSAGE_TIMERANGEQUERY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pose_graph_tools
{
template <class ContainerAllocator>
struct TimeRangeQuery_
{
  typedef TimeRangeQuery_<ContainerAllocator> Type;

  TimeRangeQuery_()
    : header()
    , source_robot_id(0)
    , destination_robot_id(0)
    , start()
    , end()  {
    }
  TimeRangeQuery_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , source_robot_id(0)
    , destination_robot_id(0)
    , start()
    , end()  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _source_robot_id_type;
  _source_robot_id_type source_robot_id;

   typedef uint32_t _destination_robot_id_type;
  _destination_robot_id_type destination_robot_id;

   typedef ros::Time _start_type;
  _start_type start;

   typedef ros::Time _end_type;
  _end_type end;





  typedef boost::shared_ptr< ::pose_graph_tools::TimeRangeQuery_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pose_graph_tools::TimeRangeQuery_<ContainerAllocator> const> ConstPtr;

}; // struct TimeRangeQuery_

typedef ::pose_graph_tools::TimeRangeQuery_<std::allocator<void> > TimeRangeQuery;

typedef boost::shared_ptr< ::pose_graph_tools::TimeRangeQuery > TimeRangeQueryPtr;
typedef boost::shared_ptr< ::pose_graph_tools::TimeRangeQuery const> TimeRangeQueryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pose_graph_tools::TimeRangeQuery_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pose_graph_tools::TimeRangeQuery_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pose_graph_tools::TimeRangeQuery_<ContainerAllocator1> & lhs, const ::pose_graph_tools::TimeRangeQuery_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.source_robot_id == rhs.source_robot_id &&
    lhs.destination_robot_id == rhs.destination_robot_id &&
    lhs.start == rhs.start &&
    lhs.end == rhs.end;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pose_graph_tools::TimeRangeQuery_<ContainerAllocator1> & lhs, const ::pose_graph_tools::TimeRangeQuery_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pose_graph_tools

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pose_graph_tools::TimeRangeQuery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_graph_tools::TimeRangeQuery_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_graph_tools::TimeRangeQuery_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_graph_tools::TimeRangeQuery_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_graph_tools::TimeRangeQuery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_graph_tools::TimeRangeQuery_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pose_graph_tools::TimeRangeQuery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8850a010b4d3f62be955d67ff24be89e";
  }

  static const char* value(const ::pose_graph_tools::TimeRangeQuery_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8850a010b4d3f62bULL;
  static const uint64_t static_value2 = 0xe955d67ff24be89eULL;
};

template<class ContainerAllocator>
struct DataType< ::pose_graph_tools::TimeRangeQuery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pose_graph_tools/TimeRangeQuery";
  }

  static const char* value(const ::pose_graph_tools::TimeRangeQuery_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pose_graph_tools::TimeRangeQuery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint32 source_robot_id        # Robot that sends this request\n"
"uint32 destination_robot_id   # Robot that receives this request\n"
"time start                    # Start of time range\n"
"time end                      # End of time range\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::pose_graph_tools::TimeRangeQuery_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pose_graph_tools::TimeRangeQuery_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.source_robot_id);
      stream.next(m.destination_robot_id);
      stream.next(m.start);
      stream.next(m.end);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimeRangeQuery_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pose_graph_tools::TimeRangeQuery_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pose_graph_tools::TimeRangeQuery_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "source_robot_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.source_robot_id);
    s << indent << "destination_robot_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.destination_robot_id);
    s << indent << "start: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.start);
    s << indent << "end: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.end);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSE_GRAPH_TOOLS_MESSAGE_TIMERANGEQUERY_H
