// Generated by gencpp from file pose_graph_tools/VLCFrameQuery.msg
// DO NOT EDIT!


#ifndef POSE_GRAPH_TOOLS_MESSAGE_VLCFRAMEQUERY_H
#define POSE_GRAPH_TOOLS_MESSAGE_VLCFRAMEQUERY_H

#include <ros/service_traits.h>


#include <pose_graph_tools/VLCFrameQueryRequest.h>
#include <pose_graph_tools/VLCFrameQueryResponse.h>


namespace pose_graph_tools
{

struct VLCFrameQuery
{

typedef VLCFrameQueryRequest Request;
typedef VLCFrameQueryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VLCFrameQuery
} // namespace pose_graph_tools


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pose_graph_tools::VLCFrameQuery > {
  static const char* value()
  {
    return "a1775d31ad21123116ba0a043abbc040";
  }

  static const char* value(const ::pose_graph_tools::VLCFrameQuery&) { return value(); }
};

template<>
struct DataType< ::pose_graph_tools::VLCFrameQuery > {
  static const char* value()
  {
    return "pose_graph_tools/VLCFrameQuery";
  }

  static const char* value(const ::pose_graph_tools::VLCFrameQuery&) { return value(); }
};


// service_traits::MD5Sum< ::pose_graph_tools::VLCFrameQueryRequest> should match
// service_traits::MD5Sum< ::pose_graph_tools::VLCFrameQuery >
template<>
struct MD5Sum< ::pose_graph_tools::VLCFrameQueryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pose_graph_tools::VLCFrameQuery >::value();
  }
  static const char* value(const ::pose_graph_tools::VLCFrameQueryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pose_graph_tools::VLCFrameQueryRequest> should match
// service_traits::DataType< ::pose_graph_tools::VLCFrameQuery >
template<>
struct DataType< ::pose_graph_tools::VLCFrameQueryRequest>
{
  static const char* value()
  {
    return DataType< ::pose_graph_tools::VLCFrameQuery >::value();
  }
  static const char* value(const ::pose_graph_tools::VLCFrameQueryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pose_graph_tools::VLCFrameQueryResponse> should match
// service_traits::MD5Sum< ::pose_graph_tools::VLCFrameQuery >
template<>
struct MD5Sum< ::pose_graph_tools::VLCFrameQueryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pose_graph_tools::VLCFrameQuery >::value();
  }
  static const char* value(const ::pose_graph_tools::VLCFrameQueryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pose_graph_tools::VLCFrameQueryResponse> should match
// service_traits::DataType< ::pose_graph_tools::VLCFrameQuery >
template<>
struct DataType< ::pose_graph_tools::VLCFrameQueryResponse>
{
  static const char* value()
  {
    return DataType< ::pose_graph_tools::VLCFrameQuery >::value();
  }
  static const char* value(const ::pose_graph_tools::VLCFrameQueryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POSE_GRAPH_TOOLS_MESSAGE_VLCFRAMEQUERY_H
