#include <std_msgs/String.h>
#include <ros/ros.h>

int main(int argc, char **argv) 
{
    ros::init(argc, argv, "my_cpp_publisher_node");
    ros::NodeHandle nh;
    ros::Publisher pub = nh.advertise<std_msgs::String>("/talker2", 10);

    ros::Rate rate(2);
    while (ros::ok())
    {
        std_msgs::String msg;
        msg.data = "The message is generated by Banafshe's first publisher.";
        pub.publish(msg);
        rate.sleep();
    }
    
}
