# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from pose_graph_tools/LoopClosuresAck.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class LoopClosuresAck(genpy.Message):
  _md5sum = "a9c7cfa8a3ce5c724d171d7076a7f930"
  _type = "pose_graph_tools/LoopClosuresAck"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint16 publishing_robot_id
uint16 destination_robot_id
uint32[] robot_src
uint32[] frame_src
uint32[] robot_dst
uint32[] frame_dst"""
  __slots__ = ['publishing_robot_id','destination_robot_id','robot_src','frame_src','robot_dst','frame_dst']
  _slot_types = ['uint16','uint16','uint32[]','uint32[]','uint32[]','uint32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       publishing_robot_id,destination_robot_id,robot_src,frame_src,robot_dst,frame_dst

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LoopClosuresAck, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.publishing_robot_id is None:
        self.publishing_robot_id = 0
      if self.destination_robot_id is None:
        self.destination_robot_id = 0
      if self.robot_src is None:
        self.robot_src = []
      if self.frame_src is None:
        self.frame_src = []
      if self.robot_dst is None:
        self.robot_dst = []
      if self.frame_dst is None:
        self.frame_dst = []
    else:
      self.publishing_robot_id = 0
      self.destination_robot_id = 0
      self.robot_src = []
      self.frame_src = []
      self.robot_dst = []
      self.frame_dst = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2H().pack(_x.publishing_robot_id, _x.destination_robot_id))
      length = len(self.robot_src)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.Struct(pattern).pack(*self.robot_src))
      length = len(self.frame_src)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.Struct(pattern).pack(*self.frame_src))
      length = len(self.robot_dst)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.Struct(pattern).pack(*self.robot_dst))
      length = len(self.frame_dst)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.Struct(pattern).pack(*self.frame_dst))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.publishing_robot_id, _x.destination_robot_id,) = _get_struct_2H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.robot_src = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.frame_src = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.robot_dst = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.frame_dst = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2H().pack(_x.publishing_robot_id, _x.destination_robot_id))
      length = len(self.robot_src)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.robot_src.tostring())
      length = len(self.frame_src)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.frame_src.tostring())
      length = len(self.robot_dst)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.robot_dst.tostring())
      length = len(self.frame_dst)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.frame_dst.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.publishing_robot_id, _x.destination_robot_id,) = _get_struct_2H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.robot_src = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.frame_src = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.robot_dst = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.frame_dst = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2H = None
def _get_struct_2H():
    global _struct_2H
    if _struct_2H is None:
        _struct_2H = struct.Struct("<2H")
    return _struct_2H
